services:
  mcp_server:
    build: ./mcp_server
    environment:
      - MCP_API_KEY=${MCP_API_KEY}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
      - GOOGLE_SA_TYPE=${GOOGLE_SA_TYPE}
      - GOOGLE_SA_PROJECT_ID=${GOOGLE_SA_PROJECT_ID}
      - GOOGLE_SA_PRIVATE_KEY_ID=${GOOGLE_SA_PRIVATE_KEY_ID}
      - GOOGLE_SA_PRIVATE_KEY=${GOOGLE_SA_PRIVATE_KEY}
      - GOOGLE_SA_CLIENT_EMAIL=${GOOGLE_SA_CLIENT_EMAIL}
      - GOOGLE_SA_CLIENT_ID=${GOOGLE_SA_CLIENT_ID}
      - GOOGLE_SA_AUTH_URI=${GOOGLE_SA_AUTH_URI}
      - GOOGLE_SA_TOKEN_URI=${GOOGLE_SA_TOKEN_URI}
      - GOOGLE_SA_AUTH_PROVIDER_CERT_URL=${GOOGLE_SA_AUTH_PROVIDER_CERT_URL}
      - GOOGLE_SA_CLIENT_CERT_URL=${GOOGLE_SA_CLIENT_CERT_URL}
      - GOOGLE_SA_UNIVERSE_DOMAIN=${GOOGLE_SA_UNIVERSE_DOMAIN}
    ports:
      - "8000:8000"
